version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: shop_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - shop_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - shop_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: shop_keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - shop_network
    depends_on:
      - db

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: shop_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=shop_backend.settings
      - MYSQL_NAME=${MYSQL_DATABASE}
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=db
    networks:
      - shop_network
    depends_on:
      - db

networks:
  shop_network:
    driver: bridge

volumes:
  shop_db_data:
